### ISSUE TITLE
Deprecated selector and one time run-cycle.

### ISSUE THREAD

**Issue by mitchell486** [Tuchkata/styles-highlighter#6]
I get the error below when I run this package for the first time since Atom has been opened. It works on the very first file I select a style token for. Then, any other tab or file will not apply the style token. I have to quit and restart Atom to get it to temporarily work again.

Please note, I have not tried replacing these manually. Just didn't quite have time today. I might be able to help troubleshoot in the future if necessary. Thank you.

-----------------------

In `styles-highlighter/styles/styles-highlighter.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
    
    * `atom-text-editor .highlights .styles-highlighter .region,
    atom-text-editor::shadow .highlights .styles-highlighter .region` => `atom-text-editor .highlights .styles-highlighter .region,
    atom-text-editor.editor .highlights .styles-highlighter .region`
    
    * `atom-text-editor .highlights .styles-highlighter.background .region,
    atom-text-editor::shadow .highlights .styles-highlighter.background .region` => `atom-text-editor .highlights .styles-highlighter.background .region,
    atom-text-editor.editor .highlights .styles-highlighter.syntax--background .region`
    
    * `atom-text-editor .highlighStyle1 .region,
    atom-text-editor::shadow .highlighStyle1 .region` => `atom-text-editor .highlighStyle1 .region,
    atom-text-editor.editor .highlighStyle1 .region`
    
    * `atom-text-editor .highlighStyle1.background .region,
    atom-text-editor::shadow .highlighStyle1.background .region` => `atom-text-editor .highlighStyle1.background .region,
    atom-text-editor.editor .highlighStyle1.syntax--background .region`
    
    * `atom-text-editor .highlighStyle2 .region,
    atom-text-editor::shadow .highlighStyle2 .region` => `atom-text-editor .highlighStyle2 .region,
    atom-text-editor.editor .highlighStyle2 .region`
    
    * `atom-text-editor .highlighStyle2.background .region,
    atom-text-editor::shadow .highlighStyle2.background .region` => `atom-text-editor .highlighStyle2.background .region,
    atom-text-editor.editor .highlighStyle2.syntax--background .region`
    
    * `atom-text-editor .highlighStyle3 .region,
    atom-text-editor::shadow .highlighStyle3 .region` => `atom-text-editor .highlighStyle3 .region,
    atom-text-editor.editor .highlighStyle3 .region`
    
    * `atom-text-editor .highlighStyle3.background .region,
    atom-text-editor::shadow .highlighStyle3.background .region` => `atom-text-editor .highlighStyle3.background .region,
    atom-text-editor.editor .highlighStyle3.syntax--background .region`
    
    * `atom-text-editor .highlighStyle4 .region,
    atom-text-editor::shadow .highlighStyle4 .region` => `atom-text-editor .highlighStyle4 .region,
    atom-text-editor.editor .highlighStyle4 .region`
    
    * `atom-text-editor .highlighStyle4.background .region,
    atom-text-editor::shadow .highlighStyle4.background .region` => `atom-text-editor .highlighStyle4.background .region,
    atom-text-editor.editor .highlighStyle4.syntax--background .region`
    
    * `atom-text-editor .highlighStyle5 .region,
    atom-text-editor::shadow .highlighStyle5 .region` => `atom-text-editor .highlighStyle5 .region,
    atom-text-editor.editor .highlighStyle5 .region`
    
    * `atom-text-editor .highlighStyle5.background .region,
    atom-text-editor::shadow .highlighStyle5.background .region` => `atom-text-editor .highlighStyle5.background .region,
    atom-text-editor.editor .highlighStyle5.syntax--background .region`
    
    * `atom-text-editor .highlighStyle6 .region,
    atom-text-editor::shadow .highlighStyle6 .region` => `atom-text-editor .highlighStyle6 .region,
    atom-text-editor.editor .highlighStyle6 .region`
    
    * `atom-text-editor .highlighStyle6.background .region,
    atom-text-editor::shadow .highlighStyle6.background .region` => `atom-text-editor .highlighStyle6.background .region,
    atom-text-editor.editor .highlighStyle6.syntax--background .region`
    
    * `atom-text-editor .highlighStyle7 .region,
    atom-text-editor::shadow .highlighStyle7 .region` => `atom-text-editor .highlighStyle7 .region,
    atom-text-editor.editor .highlighStyle7 .region`
    
    * `atom-text-editor .highlighStyle7.background .region,
    atom-text-editor::shadow .highlighStyle7.background .region` => `atom-text-editor .highlighStyle7.background .region,
    atom-text-editor.editor .highlighStyle7.syntax--background .region`
    
    * `atom-text-editor .highlighStyle8 .region,
    atom-text-editor::shadow .highlighStyle8 .region` => `atom-text-editor .highlighStyle8 .region,
    atom-text-editor.editor .highlighStyle8 .region`
    
    * `atom-text-editor .highlighStyle8.background .region,
    atom-text-editor::shadow .highlighStyle8.background .region` => `atom-text-editor .highlighStyle8.background .region,
    atom-text-editor.editor .highlighStyle8.syntax--background .region`
    
    * `atom-text-editor .highlighStyle9 .region,
    atom-text-editor::shadow .highlighStyle9 .region` => `atom-text-editor .highlighStyle9 .region,
    atom-text-editor.editor .highlighStyle9 .region`
    
    * `atom-text-editor .highlighStyle9.background .region,
    atom-text-editor::shadow .highlighStyle9.background .region` => `atom-text-editor .highlighStyle9.background .region,
    atom-text-editor.editor .highlighStyle9.syntax--background .region`
    
    * `atom-text-editor .highlighStyle10 .region,
    atom-text-editor::shadow .highlighStyle10 .region` => `atom-text-editor .highlighStyle10 .region,
    atom-text-editor.editor .highlighStyle10 .region`
    
    * `atom-text-editor .highlighStyle10.background .region,
    atom-text-editor::shadow .highlighStyle10.background .region` => `atom-text-editor .highlighStyle10.background .region,
    atom-text-editor.editor .highlighStyle10.syntax--background .region`
    
    * `atom-text-editor .occurenceHighlight .region,
    atom-text-editor::shadow .occurenceHighlight .region` => `atom-text-editor .occurenceHighlight .region,
    atom-text-editor.editor .occurenceHighlight .region`
    
    * `atom-text-editor .occurenceHighlight.background .region,
    atom-text-editor::shadow .occurenceHighlight.background .region` => `atom-text-editor .occurenceHighlight.background .region,
    atom-text-editor.editor .occurenceHighlight.syntax--background .region`
    
Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by oxygen0211** [comment]
I'll have a look at this

**Comment by Tuchkata** [comment]
Closing the issue as version 2.4.0 was release with the fix from @oxygen0211
